services:

  sqlDatabase:
    image: mcr.microsoft.com/mssql/server
    container_name: trekdb
    hostname: sqltrek
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PWD}
    env_file:
      - .env
    ports:
      - "1433:1433"
    networks:
      - library-network
  
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlDatabase
    volumes:
      - ./startrek.sql:/tmp/startrek.sql
      - ./init-sqlserver.sh:/tmp/init-sqlserver.sh
    command: /bin/bash ./tmp/init-sqlserver.sh ${SA_PWD}
    networks:
      - library-network

  dab:
    image: "mcr.microsoft.com/azure-databases/data-api-builder:latest"
    container_name: trekapi
    restart: on-failure
    env_file:
      - .env
    environment:
      MY_CONN_STRING: "Server=sqltrek;Initial Catalog=trek;User ID=sa;Password=${SA_PWD};TrustServerCertificate=True"
    volumes:
      - "./startrek.json:/App/dab-config.json"
    ports:
      - "5000:5000"
    networks:
      - library-network
    depends_on:
      - sqlDatabase

networks:
  library-network:
    driver: bridge